### ISSUE TITLE
Default device override not working for Battle.net games?

### ISSUE THREAD

**Issue by pannal** [eiz/SynchronousAudioRouter#13] opened 2017-03-30 20:16 UTC
I'm trying this with [this guide](http://twitch-guides.github.io/audio/routing-single/). Added the Battle.net folder to the SAR applications and tried Overwatch. It keeps playing back on the "Application" device, not the "Games" device.

Is this known? Do you need more technical details?

Thank you!

Edit: Windows 10 pro with ASIO4ALL

**Comment by pannal** [comment] 2017-03-31 01:52
I think this is related: https://github.com/audiorouterdev/audio-router/issues/24

**Comment by eiz** [comment] 2017-03-31 13:47
Not sure if related. SAR uses a very different method of overriding the default audio device than audio-router, but it's plausible that some anti-cheat software could break it. I don't have a copy of the game and haven't tested it.

Mind checking its handle list using Process Explorer? See if you see SarAsio.dll in its list of open files.

**Comment by pannal** [comment] 2017-03-31 14:37
Yes it has (SarAsio_x64.dll).

**Comment by skaufhold** [comment] 2017-04-02 12:04
@pannal, you were saying you added the Battle.net folder to the SAR applications; could you share the exact expression you used? Adding whole folders only works by adding a regular expression that matches everything in it, maybe something went wrong with that expression.

I wrote that guide by the way ;)

**Comment by pannal** [comment] 2017-04-02 14:22
Sure, but those work correctly, as Hearthstone and other Battle.net games work in SAR.
I was so desperate at one point, because I thought my regex was wrong, that I ended up using `.+GAMES.+`, which is the root folder for Steam *and* Battle.net.

**Comment by eiz** [comment] 2017-04-03 01:41
This appears to have nothing to do with Overwatch specifically. The problem is that Overwatch is using the XAudio2 API, which appears to have some backdoor way of getting the default audio device. It only calls IMMDeviceEnumerator::GetDevice, never IMMDeviceEnumerator::GetDefaultAudioEndpoint. Same problem happens with the basic playback example from the XAudio2 SDK samples. I'll see if I can find a solution.

**Comment by pannal** [comment] 2017-04-03 02:00
Awesome. I love the work you're doing here. Any news on a new beta?

**Comment by eiz** [comment] 2017-04-15 16:06
Need to complete a few bug fixes first. Kind of slow going atm due to work related reasons.

I'm taking a closer look now and it appears that XAudio2 is creating its renderer by calling ActivateAudioInterfaceAsync with DEVINTERFACE_AUDIO_RENDER, which goes straight into MMDevAPI's internal endpoint lookup code. ActivateAudioInterfaceAsync is implemented by an undocumented coclass ActivateAudioInterfaceWorker (E2F7A62A-862B-40AE-BBC2-5C0CA9A5B7E1) which could be intercepted, albeit at the cost of introducing a dependency on an undocumented interface. Going to give it a shot.

For completeness, other options would include hijacking the export out of MMDevAPI (very intrusive) or hijacking the top level XAudio2 COM interface (less comprehensive, other code that uses ActivateAudioInterfaceAsync wouldn't be covered). I consider CreateRemoteThread type approaches (e.g. used by audiorouter) off the table.

**Comment by eiz** [comment] 2017-04-16 22:13
This is now fixed in master. Doing some more local testing and will get a package up soon.

**Comment by pannal** [comment] 2017-04-16 22:24
You're the best. Do you have DEV instructions laying around somewhere for me to follow? I could test the latest master by myself.

I'm a developer myself (although, more Python-focused), so I should get through it.

**Comment by eiz** [comment] 2017-04-17 09:09
Here is a build. This is not adequately tested for release. Should your machine catch fire, don't say I didn't warn you.

[SynchronousAudioRouter_x64_0_13_debug_20170417.zip](https://github.com/eiz/SynchronousAudioRouter/files/925235/SynchronousAudioRouter_x64_0_13_debug_20170417.zip)

Notes:

- Not tested on anything but win10 x64
- Contains a SAR NDIS driver for future networking support. Currently does nothing, should be harmless, but ymmv
- There's significant changes to the installer
- Debug logging is on, make sure your %APPDATA%\SynchronousAudioRouter\logs doesn't fill with too much spam
- Seriously, if it bugchecks, don't be surprised, I haven't even run this under Driver Verifier yet.

I don't have actual development instructions, but basically you need VS 2015, the Windows Driver Kit, and WiX 3.10. Build defaults to test signing which you can Google how to enable loading test signed drivers. Debugging is best done with a 2 machine setup (I use a pair of Firewire cards for 1394 debugging).

**Comment by pannal** [comment] 2017-04-21 20:41
I'll try it, haven't had the time yet, sorry.

**Comment by pannal** [comment] 2017-05-13 01:03
Works. Also I don't have to quit reaper before going into sleep with the newest release (resulted in a bugcheck bluescreen).

Seems to work well for now.

**Comment by pannal** [comment] 2017-05-14 03:07
Yep, runs well.

**Comment by pannal** [comment] 2017-05-15 22:54
Ok, no issues since 3 days. Runs well, works with all games yet, and survives standby. 

Great job!

**Comment by eiz** [comment] 2017-05-16 11:04
Thanks for the feedback. I assume you were hitting the registry filter bugcheck I fixed. IRQL_NOT_LESS_THAN_OR_EQUAL or something to that effect?

**Comment by pannal** [comment] 2017-05-16 11:45
Exactly. I had to stop reaper before letting my PC go to standby before.

**Closed** 2017-07-22 17:10 UTC
