### ISSUE TITLE
Win 10 Pro 1809 17763.194 Update

### ISSUE THREAD

**Issue by hoemon** [eiz/SynchronousAudioRouter#71] opened 2019-05-30 12:48 UTC
Recent update broke SAR for my system. None of the defined virtual ins and outs are available.
Uninstallation/Reinstallation of SAR and deleting and recreating virtual input and outputs give the same result.

**Comment by amurzeau** [comment] 2019-06-02 09:16
Does the driver load correctly in the device manager ?

**Comment by amurzeau** [comment] 2019-06-02 21:27
Also, can you tell which updated got installed exactly or your previous version before 17763.194 ?

**Comment by markjfisher** [comment] 2019-06-11 08:39
I've just reinstalled windows as SAR stopped working, but thought it might have been because of some VoiceMeeter changes I'd made (desperate to get SAR working again - went for the nuke windows option).

Now, with the new windows and all updates on a base system, it's still not working.

Windows is showing me version 10.0.18362 Build 18362.

Any other information I can provide, I will do so as I really want to get this working again to use SAR/Jack/Pedalboard/Catia rather than VoiceMeeter which doesn't have as many options for routing.

**Comment by markjfisher** [comment] 2019-06-11 08:43
It's not loading in the Device Manager, here's the error:

![image](https://user-images.githubusercontent.com/1616940/59257003-0792f800-8c2d-11e9-91ed-9e2d4e5e3a4a.png)

Driver Version: 8.46.47.980

In the Events log, justing installation:

Device ROOT\MEDIA\0000 had a problem starting.

> Driver Name: oem11.inf
> Class Guid: {4d36e96c-e325-11ce-bfc1-08002be10318}
> Service: SynchronousAudioRouter
> Lower Filters: 
> Upper Filters: 
> Problem: 0x34
> Problem Status: 0xC0000428

**Comment by amurzeau** [comment] 2019-06-11 19:20
You can try to enable testsigning in boot options:
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option

This should fix the driver loading error.
I guess there is a new driver signature enforcement since some weeks by Windows

**Comment by markjfisher** [comment] 2019-06-11 20:32
do you know how much effort it will take to get it resigned?

**Comment by amurzeau** [comment] 2019-06-11 20:47
the major issue with driver signing is the cost. It seems that since fresh installs of Windows 10 1607, drivers need to be signed by microsoft itself, and that require having an EV certificat which is somewhat costly.
https://techcommunity.microsoft.com/t5/Windows-Hardware-Certification/Driver-Signing-changes-in-Windows-10-version-1607/ba-p/364894

This particular signature enforcement can be disabled by disabling secure boot, maybe its a better alternative for you. If you try that (disable secure boot in your efi bios), can you tell if it works ?

**Comment by markjfisher** [comment] 2019-06-12 14:35
After (the scary process) of enabling test-signing mode, I can confirm that SAR no longer shows an error on startup as in my earlier screen shot.

This does mean that all windows updates going forward will render SAR unusable.

I've just looked at costs for EV signing - shocking.

**Comment by hoemon** [comment] 2019-06-12 14:56
Wow, this is very sad, any long term solutions?

**Comment by amurzeau** [comment] 2019-06-16 09:46
The EV signature is needed only for fresh install of windows 10 1607, not if it was updated from the previous windows version. So I guess that's why not all users have issues.

From MSDN:

Enforcement only happens on **fresh installations**, with **Secure Boot on**, and only applies to **new kernel mode drivers (after July 29th, 2015)** :
- PCs upgrading from a release of Windows prior to Windows 10 Version 1607 will still permit installation of cross-signed drivers.
- PCs with Secure Boot OFF will still permit installation of cross-signed drivers.
- Drivers signed with an end-entity certificate issued prior to July 29th, 2015 that chains to a supported cross-signed CA will continue to be allowed.

**Comment by amurzeau** [comment] 2019-06-16 09:46
Turning Secure Boot OFF might be a better alternative than enabling testsigning.

**Comment by jnki** [comment] 2019-06-19 15:43
So, to get this straight... on a fresh install of Windows, we would need Secure Boot off permanently? Or just to install SAR, and then we can switch it back on?

**Comment by amurzeau** [comment] 2019-06-19 17:50
I didn't tried, but I think secure boot need to be disabled even after installation, else the driver probably won't be loaded.

@markjfisher @hoemon which solution did you do ?
- Downgraded windows 10 ?
- Enabled testsigning so the driver loads ?
- Disabled secure boot ?
- something else ?

**Comment by markjfisher** [comment] 2019-06-20 08:01
I did (2) and (3), as I couldn't enable test signing without disabling secure boot. Once I'd disabled secure boot, I didn't try to run it without testsigning enabled.

**Comment by amurzeau** [comment] 2020-01-02 15:41
Closing this as the issue has been worked around using test signing option.

**Closed by amurzeau** 2020-01-02 15:41 UTC

**Comment by markjfisher** [comment] 2020-02-17 16:13
I've had to revisit this.

I previously left my windows 10 in test signing mode on using `bcdedit -set TESTSIGNING ON`

However, another application won't run in this mode, so I turned it off again, and have found that SAR is still working.

I had assumed it would fail unless both secure boot was disabled AND test signing was on, but it appears it is only secure boot that needs to be left permanently off for SAR to work.
